
sudo: true
language: generic

services:
  - docker
script:
  - echo "yes!"
after_success:
  - git config --global user.email "$GITEMAIL"
  - git config --global user.name "GITUSERNAME"
  - make version
