sudo: true
language: generic
services:
  - docker
script:
  - make version
#after_success:
#  - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
#  - make build_docker_images
# safelist
branches:
  only:
  - master
